ir = "../rirs/py_rirs/rir_dining_room.wav"
num_channels = 6

[adam]
step_size = 0.6
learning_rate_decay = 0.98
decay_step_size = 1
epoch_restarts = 50
max_restarts = 1
tolerance = 1e-5

[spsa]
alpha = 0.01
gamma = 0.101
step_size = 0.9
evaluation_step_size = 0.9
max_iterations = 1e6
tolerance = 1e-5

[lbfgs]
num_basis = 10
max_iterations = 1000
wolfe = 0.9
min_gradient_norm = 1e-6
factor = 1e-15
max_line_search = 50
min_step = 1e-20
max_step = 1e20

[cmaes]
population_size = 0
max_iterations = 1000
tolerance = 1e-5
step_size = 0